name: "{{name.snakeCase()}}"
description: A Flutter application using the MVVM architecture profile.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  # {{#useProvider}}
  provider: ^6.1.2
  # {{/useProvider}}
  # {{#useRiverpod}}
  flutter_riverpod: ^2.6.1
  # {{/useRiverpod}}
  # {{^useProvider}}
  # {{^useRiverpod}}
  flutter_bloc: ^9.1.0
  # {{/useRiverpod}}
  # {{/useProvider}}
  # {{^useRouter}}
  go_router: ^14.0.0
  # {{/useRouter}}

  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0
  retrofit: ^4.9.2
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  injectable_generator: ^2.6.1
  retrofit_generator: ^10.2.6
  json_serializable: ^6.14.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
